websites:
  - name: "Instagram"
    base_url: "https://instagram.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg" 
    errorMsg: "<title>Page not found • Instagram</title>"

  - name: "Twitter/X"
    base_url: "https://twitter.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "unknown"
    errorCode: 403

  - name: "GitHub"
    base_url: "https://github.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404

  - name: "Reddit"
    base_url: "https://www.reddit.com/user/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<title>Reddit - Dive into anything</title>"

  - name: "Facebook"
    base_url: "https://www.facebook.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg" 
    errorMsg: "<title>Facebook</title>"

  - name: "YouTube"
    base_url: "https://www.youtube.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "TikTok"
    base_url: "https://www.tiktok.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "profilePresence"
    errorMsg: "shareMeta"

  - name: "About Me"
    base_url: "https://about.me/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Independent Academia"
    base_url: "https://independent.academia.edu/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
  
  - name: "Airbit"
    base_url: "https://airbit.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Airliners"
    base_url: "https://www.airliners.net/user/{}/profile/photos"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Duolingo"
    base_url: "https://www.duolingo.com/profile/{}"
    url_probe: "https://www.duolingo.com/2017-06-30/users?username={}"
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "{\"users\":[]}"

  - name: "Pinterest"
    base_url: "https://www.pinterest.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<title></title>"

  - name: "VSCO"
    base_url: "https://vsco.co/{}/gallery"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Snapchat"
    base_url: "https://www.snapchat.com/add/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Threads"
    base_url: "https://www.threads.net/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<title>Threads</title>"

  - name: "Tumblr"
    base_url: "https://www.tumblr.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Keybase"
    base_url: "https://keybase.io/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Wattpad"
    base_url: "https://www.wattpad.com/user/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Mastodon Social"
    base_url: "https://mastodon.social/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "MSTDN Social"
    base_url: "https://mstdn.social/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Mas.to"
    base_url: "https://mas.to/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Mastodon World"
    base_url: "https://mastodon.world/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
  - name: "Fosstodon"
    base_url: "https://fosstodon.org/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Hachyderm"
    base_url: "https://hachyderm.io/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Vivaldi Social"
    base_url: "https://social.vivaldi.net/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Techhub Social"
    base_url: "https://techhub.social/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Wakatime"
    base_url: "https://wakatime.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Twitch"
    base_url: "https://twitch.tv/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<meta property='og:description' content='Twitch is the world&#39;s leading video platform and community for gamers.'>"

  - name: "Rumble"
    base_url: "https://rumble.com/c/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404


  - name: "Kick"
    base_url: "https://kick.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "unknown"
    errorCode: 403
    
  - name: "Yandex Dzen"
    base_url: "https://dzen.ru/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
    cookies:
    - name: "zen_sso_checked"
      value: "1"


  - name: "YVision KZ"
    base_url: "https://yvision.kz/u/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Giphy"
    base_url: "https://giphy.com/channel/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Bluesky"
    base_url: "https://bsky.app/profile/{}.bsky.social"
    url_probe: "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor={}.bsky.social"
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "{\"error\":\"InvalidRequest\",\"message\":\"Profile not found\"}"

  - name: "9GAG"
    base_url: "https://9gag.com/u/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
    cookies:
    - name: "ts1"
      value: "4b134fab9439a52a1a8d1789265b0404523ccb08"

  - name: "Flickr"
    base_url: "https://flickr.com/photos/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Behance"
    base_url: "https://behance.net/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
  
  - name: "Buy Me a Coffee"
    base_url: "https://buymeacoffee.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
  
  - name: "Ko-fi"
    base_url: "https://ko-fi.com/{}"
    url_probe: ""
    follow_redirects: false
    errorType: "status_code"
    errorCode: 302

  - name: "Tinder"
    base_url: "https://tinder.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: '<title data-react-helmet="true">Tinder | Dating, Make Friends &amp; Meet New People</title>'

  # LinkedIn requires authorisation for some profiles; therefore it is reported as an "unknown" to avoid false negatives
  # For example, https://www.linkedin.com/in/ben can be viewed without authorisation but mine cannot.
  - name: "LinkedIn"
    base_url: "https://www.linkedin.com/in/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "unknown"
    errorCode: 999

  - name: "Vimeo"
    base_url: "https://vimeo.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Medium"
    base_url: "https://medium.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: '<title data-rh="true">Medium</title>'

  - name: "Spotify"
    base_url: "https://open.spotify.com/user/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404
  
  - name: "Clubhouse"
    base_url: "https://www.joinclubhouse.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Foursquare"
    base_url: "https://foursquare.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "SoundCloud"
    base_url: "https://soundcloud.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Patreon"
    base_url: "https://www.patreon.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Vero"
    base_url: "https://vero.co/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "_not-found-page-container_onczy_1"

  - name: "Figma"
    base_url: "https://www.figma.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 202


  - name: "Linktree"
    base_url: "https://www.linktr.ee/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: '"statusCode":404'

  - name: "Beacons.ai"
    base_url: "https://beacons.ai/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 403

  - name: "Bio.link"
    base_url: "https://bio.link/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Milkshake"
    base_url: "https://msha.ke/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Snipfeed"
    base_url: "https://snipfeed.co/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Ayo.so"
    base_url: "https://ayo.so/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Carrd"
    base_url: "https://{}.carrd.co"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Steam"
    base_url: "https://steamcommunity.com/id/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<title>Steam Community :: Error</title>"

  - name: "Dev Community"
    base_url: "https://dev.to/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Daily.dev"
    base_url: "https://app.daily.dev/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: '<p class="text-text-tertiary typo-callout">You’re not supposed to be here.</p>'

  - name: "HackerNews"
    base_url: "https://news.ycombinator.com/user?id={}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: 'No such user.'

  - name: "HackTheBox Forum"
    base_url: "https://forum.hackthebox.com/u/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "1337x.to"
    base_url: "https://www.1337x.to/user/{}/"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<p> Bad Username.</p>"

  - name: "7Cups"
    base_url: "https://www.7cups.com/@{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "8Tracks"
    base_url: "https://8tracks.com/{}"
    url_probe: "https://8tracks.com/users/check_username?login={}&format=jsonh"
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: '{"available":true}'

  - name: "All My Links"
    base_url: "https://allmylinks.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Aniworld.to"
    base_url: "https://aniworld.to/user/profil/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<title>Profil | AniWorld.to - Animes gratis legal online ansehen</title>"

  - name: "Anilist"
    base_url: "https://anilist.co/user/{}/"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: "<title>AniList</title>"

  - name: "Apple Developers"
    base_url: "https://developer.apple.com/forums/profile/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Apple Discussions"
    base_url: "https://discussions.apple.com/profile/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Archive Of Our Own (AO3)"
    base_url: "https://archiveofourown.org/users/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code"
    errorCode: 404

  - name: "Telegram"
    base_url: "https://t.me/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: 'If you have <strong>Telegram</strong>, you can contact'

  - name: "LastFM"
    base_url: "https://last.fm/user/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404


  - name: "Chess"
    base_url: "https://www.chess.com/member/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404


  - name: "Lichess"
    base_url: "https://lichess.org/@/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404

  - name: "Codeacadmey"
    base_url: "https://www.codecademy.com/profiles/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "errorMsg"
    errorMsg: '<title>Profile Not Found | Codecademy</title>'


  - name: "Gitlab"
    base_url: "https://gitlab.com/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 403

  - name: "Disqus"
    base_url: "https://disqus.com/by/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404

  - name: "Docker Hub"
    base_url: "https://hub.docker.com/u/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404

  - name: "Kali Linux Forums"
    base_url: "https://forums.kali.org/u/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404


  - name: "Imgur"
    base_url: "https://imgur.com/user/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "unknown" 
    errorCode: 200

  - name: "GameFAQs Community"
    base_url: "https://gamefaqs.gamespot.com/community/{}"
    url_probe: ""
    follow_redirects: true
    errorType: "status_code" 
    errorCode: 404
